name: Coverage on PR

on:
  pull_request:

jobs:
  pr_scan:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 20.9.0
        uses: actions/setup-node@v2
        with:
          node-version: 20.9.0

      - name: Installation of npm
        run: |
          npm install

      - name: Jest report
        uses: ArtiomTr/jest-coverage-report-action@v2.0-rc.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          test-script: "npm run test:full-coverage"
          threshold: 90
          annotations: none
