name: Manual promote release in prod

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Which release to promote in prod:'
        type: string
        required: true

defaults:
  run:
    shell: bash

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: write    # This is required for actions/checkout

jobs:
  manual-promote-release-in-prod:
    if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
    strategy:
      matrix:
        environment: [uat]

    name: "manual-promote-release-in-prod"
    runs-on: ubuntu-latest
    environment: ${{ matrix.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Configure uat AWS Credentials
        uses: aws-actions/configure-aws-credentials@67fbcbb121271f7775d2e7715933280b06314838
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Pull pre-release = ${{ inputs.release }} from uat S3
        run: |
          aws s3api get-object --bucket ${{ vars.BUCKET_NAME_ARTIFACTS }} --key ${{ inputs.release }}.zip ./${{ inputs.release }}.zip

      - name: Configure prod AWS Credentials
        uses: aws-actions/configure-aws-credentials@67fbcbb121271f7775d2e7715933280b06314838
        with:
          role-to-assume: ${{ secrets.PROD_IAM_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Push release on prod S3
        run: |
          aws s3 cp ${{ inputs.release }}.zip s3://${{ vars.PROD_BUCKET_NAME_ARTIFACTS }}/
